# Generated by Django 4.1 on 2022-09-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parientes',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
